### ISSUE TITLE
READMEに開発の仕方を追加

### ISSUE THREAD

**Issue by miily8310s** [pastak/vaccines-kyoto-city-faq#12]
READMEに開発の仕方がないため、追加の提案になります。
（意外とOSS貢献あんまりしたことないけど貢献したい人いるんじゃないかなと思います。）
サイトの寿命は短いと思ってらっしゃるかもしれませんが一考していただけると…。

もし追加するなら、以下の書き方で考えてみたのでしょうがどうでしょうか？

```
## 開発の仕方
### 必要なもの
- GitHubアカウント（なければ[ここ](https://github.com/)で作成できます。）
- Node.js（[こちら](https://nodejs.org/ja/download/)からダウンロードできます。）
### パッケージインストール

npm install

### ローカルプレビュー
コマンドを実行すると、 http://localhost:3000/vaccines-kyoto-city-faq/ から確認することができます。

npm run dev

```

※開発の仕方は[こちらのリポジトリ](https://github.com/omegasisters/homepage/blob/master/README.md)を参考にさせていただきました。

**Comment by pastak** [comment]
是非Pull Requestください 👍

**Comment by pastak** [comment]
頂いて提案をベースにREADMEを更新しました

**Comment by miily8310s** [comment]
> 頂いて提案をベースにREADMEを更新しました

返信に気づかず申し訳無いです…ありがとうございます！自分もこれで問題ないです👍
