### ISSUE TITLE
ESLint/Prettierの追加の提案

### ISSUE THREAD

**Issue by miily8310s** [pastak/vaccines-kyoto-city-faq#2]
コードを軽く拝見したのですが、全体的に横長でコードの可読性が良くないように感じてしまいます。
そこでESLint/Prettierの追加を検討してもらえないでしょうか？元々追加する予定がないのなら本issueはcloseしていただいて構いません。

**Comment by pastak** [comment]
色々サボっている結果、`index.html`にベタっと貼れば良いHTML断片もReact側に書いていて、そこに日本語がいっぱいある結果そうなっているという印象です。

eslintやPrettierなどについては個人的にも入れても良いなと思っているんですが、そんなに長期に渡ってメンテすることもないだろうと願っているので、とりあえず導入をサボっている形です。

ただ入れてもらうのは歓迎なので、Pull Requestもらえれば非常にありがたいです。

**Comment by miily8310s** [comment]
@pastak 
PR作成しましたので時間あるときにでも確認お願いします！
